# Generated by Django 4.0.1 on 2022-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pic/male-avatar.jpg', upload_to='profile_pic'),
        ),
    ]
