# Generated by Django 4.0.1 on 2022-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('pending', 'PENDING'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED')], default='new', max_length=200, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('images1', models.ImageField(blank=True, upload_to='images/')),
                ('images2', models.ImageField(blank=True, upload_to='images/')),
                ('images3', models.ImageField(blank=True, upload_to='images/')),
                ('ram', models.CharField(max_length=200, null=True)),
                ('storage', models.CharField(max_length=200, null=True)),
                ('camara', models.CharField(max_length=200, null=True)),
                ('battery', models.CharField(max_length=200, null=True)),
                ('processor', models.CharField(max_length=200, null=True)),
                ('display', models.CharField(max_length=200, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
