# Generated by Django 4.0.1 on 2022-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_rename_cartitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
