# Generated by Django 4.0.1 on 2022-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_orderitem_options_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(default='No', max_length=200, null=True),
        ),
    ]
