# Generated by Django 4.0.1 on 2022-02-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
