# Generated by Django 4.0.1 on 2022-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
