# Generated by Django 4.0.1 on 2022-02-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('UserCancelled', 'UserCancelled')], default='New', max_length=200, null=True),
        ),
    ]
