# Generated by Django 4.0.1 on 2022-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return', 'Return'), ('UserCancelled', 'UserCancelled')], default='New', max_length=200, null=True),
        ),
    ]
