# Generated by Django 4.0.1 on 2022-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy_now',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
