# Generated by Django 4.0.1 on 2022-03-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PayPal', 'PayPal'), ('RazorPay', 'RazorPay')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
