# Generated by Django 4.0.1 on 2022-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_order_payment_method_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
