# Generated by Django 4.0.1 on 2022-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
