# Generated by Django 4.0.1 on 2022-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_alter_signupcoupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupen',
            field=models.IntegerField(null=True),
        ),
    ]
