# Generated by Django 4.0.1 on 2022-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_alter_order_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupen',
            field=models.IntegerField(null=True),
        ),
    ]
