# Generated by Django 4.0.1 on 2022-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_alter_order_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcoupon',
            name='proceed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
