# Generated by Django 4.0.1 on 2022-03-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0028_signupcoupon_proceed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category_off', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_off',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.brand'),
        ),
    ]
