# Generated by Django 4.0.1 on 2022-03-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_off',
            field=models.IntegerField(default=0),
        ),
    ]
