# Generated by Django 4.0.1 on 2022-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
