# Generated by Django 4.0.1 on 2022-03-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0036_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_off',
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
                ('proceed', models.BooleanField(default=False, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.product')),
            ],
        ),
    ]
