# Generated by Django 4.0.1 on 2022-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0038_remove_offer_product_product_product_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
