# Generated by Django 4.0.1 on 2022-03-31 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_offer_product_alter_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='available',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='proceed',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(choices=[('Product', 'Product'), ('Category', 'Category')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.offer'),
        ),
    ]
